### ISSUE TITLE
Authorization Failure

### ISSUE THREAD

**Issue by wshackle** [neo4j-examples/movies-java-jdbc#1]
When attempting to run the example, I get an Authorization Failure. I expected it to just connect to a local database and therefore not need Authorization. It is not clear to me what URL it is using or where authentication info should be stored. I can browse the database at http://localhost:7474/browser/ without specifying any username or password.

```
shackle@ying:~/NetBeansProjects/movies-java-jdbc$ mvn compile exec:java                                  
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Neo4j Movies Demo 2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.3:resources (default-resources) @ neo4j-movies ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ neo4j-movies ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] >>> exec-maven-plugin:1.2.1:java (default-cli) @ neo4j-movies >>>
[INFO] 
[INFO] <<< exec-maven-plugin:1.2.1:java (default-cli) @ neo4j-movies <<<
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:java (default-cli) @ neo4j-movies ---
p = {java.runtime.name=Java(TM) SE Runtime Environment, sun.boot.library.path=/usr/local/jdk1.8.0_60/jre/lib/amd64, java.vm.version=25.60-b23, java.vm.vendor=Oracle Corporation, java.vendor.url=http://java.oracle.com/, guice.disable.misplaced.annotation.check=true, path.separator=:, java.vm.name=Java HotSpot(TM) 64-Bit Server VM, file.encoding.pkg=sun.io, user.country=US, sun.java.launcher=SUN_STANDARD, sun.os.patch.level=unknown, java.vm.specification.name=Java Virtual Machine Specification, user.dir=/home/shackle/NetBeansProjects/movies-java-jdbc, java.runtime.version=1.8.0_60-b27, java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment, java.endorsed.dirs=/usr/local/jdk1.8.0_60/jre/lib/endorsed, os.arch=amd64, java.io.tmpdir=/tmp, line.separator=
, java.vm.specification.vendor=Oracle Corporation, os.name=Linux, classworlds.conf=/usr/share/maven/bin/m2.conf, sun.jnu.encoding=UTF-8, java.library.path=:/usr/local/OpenDDS/lib/::/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib, java.specification.name=Java Platform API Specification, java.class.version=52.0, sun.management.compiler=HotSpot 64-Bit Tiered Compilers, os.version=3.13.0-66-generic, user.home=/home/shackle, user.timezone=America/New_York, java.awt.printerjob=sun.print.PSPrinterJob, file.encoding=UTF-8, java.specification.version=1.8, java.class.path=/usr/share/maven/boot/plexus-classworlds-2.x.jar, user.name=shackle, java.vm.specification.version=1.8, sun.java.command=org.codehaus.plexus.classworlds.launcher.Launcher compile exec:java, java.home=/usr/local/jdk1.8.0_60/jre, sun.arch.data.model=64, user.language=en, java.specification.vendor=Oracle Corporation, awt.toolkit=sun.awt.X11.XToolkit, java.vm.info=mixed mode, java.version=1.8.0_60, securerandom.source=file:/dev/./urandom, java.ext.dirs=/usr/local/jdk1.8.0_60/jre/lib/ext:/usr/java/packages/lib/ext, sun.boot.class.path=/usr/local/jdk1.8.0_60/jre/lib/resources.jar:/usr/local/jdk1.8.0_60/jre/lib/rt.jar:/usr/local/jdk1.8.0_60/jre/lib/sunrsasign.jar:/usr/local/jdk1.8.0_60/jre/lib/jsse.jar:/usr/local/jdk1.8.0_60/jre/lib/jce.jar:/usr/local/jdk1.8.0_60/jre/lib/charsets.jar:/usr/local/jdk1.8.0_60/jre/lib/jfr.jar:/usr/local/jdk1.8.0_60/jre/classes, java.vendor=Oracle Corporation, maven.home=/usr/share/maven, file.separator=/, java.vendor.url.bug=http://bugreport.sun.com/bugreport/, sun.io.unicode.encoding=UnicodeLittle, sun.cpu.endian=little, sun.desktop=gnome, sun.cpu.isalist=}
Oct 21, 2015 11:24:45 AM org.restlet.ext.httpclient.HttpClientHelper start
INFO: Starting the Apache HTTP client
log4j:WARN No appenders could be found for logger (org.apache.http.impl.conn.tsccm.ThreadSafeClientConnManager).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Oct 21, 2015 11:24:45 AM org.restlet.engine.security.AuthenticatorUtils parseRequest
WARNING: Couldn't find any helper support the HTTP_None challenge scheme.
[WARNING] 
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:297)
        at java.lang.Thread.run(Thread.java:745)
Caused by: Unauthorized (401) - Unauthorized
        at org.restlet.resource.ClientResource.doError(ClientResource.java:612)
        at org.restlet.resource.ClientResource.handleInbound(ClientResource.java:1202)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:1069)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:1044)
        at org.restlet.resource.ClientResource.handle(ClientResource.java:950)
        at org.restlet.resource.ClientResource.get(ClientResource.java:658)
        at org.neo4j.jdbc.rest.Resources.readJsonFrom(Resources.java:97)
        at org.neo4j.jdbc.rest.Resources$DiscoveryClientResource.readInformation(Resources.java:135)
        at org.neo4j.jdbc.rest.Resources.getDiscoveryResource(Resources.java:65)
        at org.neo4j.jdbc.rest.Resources.getDiscoveryResource(Resources.java:60)
        at org.neo4j.jdbc.Neo4jConnection.getDiscoveryResource(Neo4jConnection.java:80)
        at org.neo4j.jdbc.Neo4jConnection.createExecutor(Neo4jConnection.java:69)
        at org.neo4j.jdbc.Neo4jConnection.<init>(Neo4jConnection.java:61)
        at org.neo4j.jdbc.Connections$4.doCreate(Connections.java:51)
        at org.neo4j.jdbc.Connections.create(Connections.java:63)
        at org.neo4j.jdbc.Driver.connect(Driver.java:64)
        at org.neo4j.jdbc.Driver.connect(Driver.java:36)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at example.jdbc.executor.JdbcCypherExecutor.<init>(JdbcCypherExecutor.java:18)
        at example.jdbc.executor.JdbcCypherExecutor.<init>(JdbcCypherExecutor.java:14)
        at example.jdbc.movies.MovieService.createCypherExecutor(MovieService.java:32)
        at example.jdbc.movies.MovieService.<init>(MovieService.java:22)
        at example.jdbc.movies.MovieServer.main(MovieServer.java:16)
        ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.726s
[INFO] Finished at: Wed Oct 21 11:24:45 EDT 2015
[INFO] Final Memory: 14M/189M
Oct 21, 2015 11:24:45 AM org.restlet.ext.httpclient.HttpClientHelper stop
INFO: Stopping the HTTP client
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:java (default-cli) on project neo4j-movies: An exception occured while executing the Java class. null: InvocationTargetException: Unauthorized -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
shackle@ying:~/NetBeansProjects/movies-java-jdbc$ 
```

**Comment by kuyezhiying** [comment]
You got the authorization failure info because you initial connection without users account, like this(which is also how the readme.adoc of example movies-java-jdbc project wrote):
Connection con = DriverManager.getConnection("jdbc:neo4j://localhost:7474/");
However, the program will fill to start he apache http client with this connection ,you should also add the user info including username and password, just like how you use the jdbc connection with relational database. The format is like below:
Connection con = DriverManager.getConnection("jdbc:neo4j://localhost:7474/", "neo4j", "123456");

**Comment by kuyezhiying** [comment]
The password is set when you open the neo4j browser, which has a default value "neo4j"(same to the username).

**Comment by jexp** [comment]
It does not set up a database, as it says here: https://github.com/neo4j-examples/movies-java-jdbc#run-locally you have to setup the movie dataset.

Please also provide the username "neo4j" and the new password you chose as part of the setup config.
